### ISSUE TITLE
Requested store is not found

### ISSUE THREAD

**Issue by cdolbergr** [trustpilot/plugin-magento2#42] opened 2019-08-22 14:59 UTC
I am currently setting up your module, but I am running into problems when trying to configure the module for my different websites and stores.

Everything seems to work as expected when switching between stores, but as soon as I switch to another website I run into trouble. Please see the error underneath:

`1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested store is not found

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Requested store is not found
#0 /Applications/MAMP/htdocs/example/vendor/magento/module-store/Model/StoreManager.php(167): Magento\Store\Model\StoreRepository->getById(4)

#1 /Applications/MAMP/htdocs/example/vendor/magento/module-catalog/Model/ResourceModel/Collection/AbstractCollection.php(96): Magento\Store\Model\StoreManager->getStore(4)

#2 /Applications/MAMP/htdocs/example/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(585): Magento\Catalog\Model\ResourceModel\Collection\AbstractCollection->setStore(4)

#3 /Applications/MAMP/htdocs/example/vendor/trustpilot/module-reviews/Helper/Data.php(208): Magento\Catalog\Model\ResourceModel\Product\Collection->setStore(4)

#4 /Applications/MAMP/htdocs/example/vendor/trustpilot/module-reviews/Block/System/Config/Admin.php(66): Trustpilot\Reviews\Helper\Data->getFirstProduct()`

In the line where "getStore(4)" is has the id of the website and not the store, which seems wrong to me. Any help would be much appreciated.

**Comment by shaggywolfhound** [comment] 2019-08-22 15:32
We get the same problem on our stores.  If you do an sql query:

select * from core_config_data where path like '%trust%' and scope like '%web%'

You'll see the entries your talking about.  I don't believe that this entry should be created and is the cause of yours and my problem.

**Comment by shaggywolfhound** [comment] 2019-08-23 08:53
appears to create entry with the following path entries with scope:websites
trustpilot/trustpilot_general_group/failed_orders
trustpilot/trustpilot_general_group/past_orders

**Comment by vdabar** [comment] 2019-09-17 10:27
Sorry for late response, Issue was fixed in the newest release https://github.com/trustpilot/plugin-magento2/commit/3e488d04d2661c03b2f6e02d476e803cd18f1df0. Thank you for reporting it!

**Closed by vdabar** 2019-09-17 10:27 UTC
