### ISSUE TITLE
Call to CURL produces output of [] and breaks orderSave and checkout

### ISSUE THREAD

**Issue by php4umagento** [trustpilot/plugin-magento2#13] opened 2018-10-20 15:40 UTC
When curl is called, there is a string returned to the buffer rather than returned to variable

Please use CURLOPT_RETURNTRANSFER true

**Comment by ryanengland** [comment] 2018-10-22 10:31
We're getting this too. Pretty urgent! This is fixed by the pull request submitted here: https://github.com/trustpilot/plugin-magento2/pull/12

**Comment by maksim-grib** [comment] 2018-10-23 06:02
Strange thing that it is not reproducible anymore, but it was yesterday and since 18th of October I believe. Looks like they fixed this by changing the API. Previously it responded with empty response, but this was changed to an empty array (by mistake?), and now it is again empty response.

Still this should be fixed by setting *CURLOPT_RETURNTRANSFER* flag for ALL request (right now it is used only for GET requests), so I think merge request above is mistaken as well.

Here is the patch you can apply to be sure you won't encounter this issue in the future in case of API changes (assuming module installed via composer in the vendor directory). 

`git apply TRUSTPILOT_HTTP_CLIENT_FIX.patch`

[TRUSTPILOT_HTTP_CLIENT_FIX.patch.zip](https://github.com/trustpilot/plugin-magento2/files/2504680/TRUSTPILOT_HTTP_CLIENT_FIX.patch.zip)

**Comment by vilgro** [comment] 2018-10-24 09:08
Thank you for starting the discussion about this issue and suggesting the possible fix for it. Trustpilot team has determined that the problem was related to response data from Trustpilot API.  Fix was deployed on 22nd of Oct . Going forward such behaviour will be validated by specific testing, therefore similar problems should not occur.

**Closed** 2018-10-24 09:08 UTC
